slowa = ['balkon', 'banany', 'beczka', 'biurko',
        'bramka', 'chmura', 'chwila', 'ciemny',
        'ciepło', 'ciasto', 'czapka', 'czarny',
        'cztery', 'daleki', 'daszek', 'dialog',
        'dobrze', 'dolina', 'drabina', 'drewno',
        'drzewo', 'duszno', 'głowa', 'gorący', 'gruby', 
        'grzyby', 'jajko', 'jasny', 'jeleń', 'jesień', 'język',
        'kaczka', 'kaktus', 'kamień', 'kanapa', 'kelner', 'kijek',
        'klamka', 'komar', 'koniec', 'koszyk', 'krater', 'kubek', 
        'kurtka', 'kwiaty', 'lampka', 'lekarz', 'leśny', 'listek',
        'lustro', 'magnes', 'małpa', 'masło', 'miasto', 'młody',
        'mostek', 'motyl', 'myszka', 'nauka', 'niebo', 'nitka',
        'nożyce', 'numer', 'nurek', 'obiad', 'obraz', 'obuwie',
        'ocean', 'odzież', 'ogonek', 'ogród', 'ołówek', 'opona',
        'orzech', 'osoba', 'paczka', 'paliwo', 'papier', 'papuga',
        'pasek', 'piasek', 'pieprz', 'piesek', 'piętro', 'piłka',
        'piorun', 'pisak', 'pismo', 'plakat', 'plaża', 'plecak',
        'pociąg', 'poczta', 'pogoda', 'pokój', 'pomoc', 'potok',
        'powiat', 'poziom', 'prosty']
